services:
  my_app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    image: lab3:v-1
    environment:
      PORT: "5003"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "12345"
      POSTGRES_DB: "Lab3"
      POSTGRES_HOST: "db"
      JWT_SECRET_KEY: "Jg5Dl2yBdU8GIbcsH1JRDw=="
    ports:
      - "5003:5003"
    depends_on:
      - db
  db:
    image: postgres:15.4-alpine3.18
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "12345"
      POSTGRES_DB: "Lab3"
      POSTGRES_HOST: "db"
      JWT_SECRET_KEY: "Jg5Dl2yBdU8GIbcsH1JRDw=="
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: